version: '3.1'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: e-academy-api
    ports:
      - '8000:8000'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: e-academy-frontend
    stdin_open: true
    ports:
      - '3000:3000'
  db:
    image: postgres
    container_name: e-academy-db
    ports:
      - 5555:5432
    volumes:
      - e-academy-db-data:/data/postgresql/e-academy
    environment:
      - POSTGRES_PASSWORD=Password1!
      - POSTGRES_USER=root
      - TZ=GMT+7
      - PGTZ=GMT+7
    restart: "unless-stopped"

volumes:
  e-academy-db-data:
    driver: local